-- insert random data
-- insert into users (username, password) select random(), generate_series(0,10000);

-- REAL DATA

insert into users (firstname, lastname, username, password) values
('Muhammadxon', 'Najimov', 'muhammad', 'i@Mr00Tuser');

insert into users (firstname, lastname, username, password) values
('Azizullo', 'Adhamjonov', 'adhamjonov', 'i@Mr00Tuser');

insert into users (firstname, lastname, username, password) values
('Temurbek', 'Adhamov', 'adhamov', 'P@$$w0rD');

insert into users (firstname, lastname, username, password) values
('Ali', 'Zairov', 'zairov', 'i@Mr00Tuser');

insert into users (firstname, lastname, username, password) values
('Muhammadjavohir', 'Sur''atov', 'mayoq', 'i@Mr00Tuser');

insert into users (firstname, lastname, username, password) values
('Saud', 'Abdulawaheed', 'saud', 'i@Mr00Tuser');

insert into users (firstname, lastname, username, password) values
('Alisher', 'Kasimov', 'kasimov', 'i@Mr00Tuser');

insert into permissions (action, user_id) values (1, 1), (2, 1);

insert into branches (name) values ('Chilonzor'), ('Xadra'), ('Olmazor');

insert into rooms (branch_id, room_name) values (1, 1), (1, 2), (1, 3);
insert into rooms (branch_id, room_name) values (2, 1), (2, 2);
insert into rooms (branch_id, room_name) values (3, 1), (3, 2), (3, 3), (3, 4), (3, 5);

insert into courses (name) values ('Foundation'), ('Front-End Development'), ('NodeJs'), ('Flutter Mobile'), ('Go');

insert into groups (price, lessons, user_id, course_id, branch_id, room_id) values
(8000000, 80, 1, 5, 1, 1)
;

insert into teachers (user_id) values
(1), (3), (5), (6), (7)
;

insert into pariticipants (discount, raise, role, initial_lesson, group_id, user_id) values
(10, 20, 1, 2, 1, 3)
;

insert into lessons (group_id) values (3), (3), (3), (3), (3);
;

insert into deposits (account_id, operator_id, amount) values (1, 2, 10000000);
;

create table deposits (
	deposit_id int4 generated by default as identity (start with 1 increment by 1) primary key,
	account_id int4 not null references users (user_id),
	operator_id int4 not null references users (user_id),
	amount decimal(16, 2) default 0,
	deposit_time timestamp with time zone default current_timestamp
);